disabled_rules: # rule identifiers to exclude from running
opt_in_rules: # some rules are only opt-in
  - empty_count
included: # paths to include during linting. `--path` is ignored if present.

excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 - ThirdParty

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning
force_try: warning
line_length:
  warning: 200
  error: 240
trailing_comma:
  mandatory_comma: true
# rules that have both warning and error levels, can set just the warning level
# implicitly
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
